//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.27 at 11:39:45 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/UserView", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ds.appmanager.model;
